spring:
  application:
    name: fintech-payment-api

  config:
    import: "optional:dotenv:.env"

#for development, you can use the following properties directly in application.yml or set them in .env file
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fintechdb}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      #for development
      ddl-auto: update
    show-sql: true
  jwt:
    secret: ${JWT_SECRET:CSrYLJouBPSkpRtuQ9npnkOa52xsOp26QSrVgBg9XaM=}
    expiration-ms: ${JWT_EXPIRATION_MS:3600000} # 1 hour in milliseconds

  server:
    port: 8080

logging:
  level:
    org.springframework.security: DEBUG
